#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

src_dir="/usr/src/matomo"

if [[ ! -f "${APP_ROOT}/piwik.php" ]]; then
    echo >&2 "${APP_NAME} not found in ${APP_ROOT} - copying now..."
    rsync -a "${src_dir}/" "${APP_ROOT}/"
    echo >&2 "Complete! ${APP_NAME} has been successfully copied to ${APP_ROOT}"
else
    latest_ver=$(php "${src_dir}/console"  -V | grep -oE '[0-9]+(\.[0-9]+){2}')
    current_ver=$(php "${APP_ROOT}/console"  -V | grep -oE '[0-9]+(\.[0-9]+){2}')

    res=$(compare-semver.sh "${latest_ver}" "${current_ver}" ">")

    if [[ "${res}" == 0 ]]; then
        echo "Current version of ${APP_NAME} is outdated (${current_ver}), updating to ${latest_ver}..."
        rsync -a "${src_dir}/" "${APP_ROOT}/"
        echo "Complete! ${APP_NAME} has been successfully updated to ${latest_ver}"
    fi
fi
